secrets:
  traefik_cf-dns-api-token:
  # The DNS provider's DNS API token.
    external: true
  traefik_cf-zone-api-token:
  # The DNS provider's zone API token.
    external: true
services:
  adminer:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.adminer_secure.middlewares=auth
      - traefik.http.routers.adminer_secure.tls.certresolver=default
  dargstack-example:
    command: (( prune ))
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.dargstack-example_secure.tls.certresolver=default
    image: dargmuesli/dargstack-example:1.3.1@sha256:cbf17a357cd42e2ddcb62425d61e25b4220b9c998e878183a540ae2dc4a0683b
    volumes:
    - (( replace ))
    - acme_data:/etc/nginx/cert/
  traefik:
    command:
    - (( prepend ))
    - --certificatesResolvers.default.acme.email=${STACK_ACME_EMAIL}
    - --certificatesResolvers.default.acme.storage=/etc/traefik/acme/acme.json
    - --certificatesResolvers.default.acme.dnsChallenge.provider=${STACK_ACME_PROVIDER}
    deploy:
      labels:
      - (( append ))
      - traefik.http.middlewares.auth.basicauth.users=${STACK_AUTH_BASIC}
      - traefik.http.routers.traefik_secure.middlewares=auth
      - traefik.http.routers.traefik_secure.tls.certresolver=default
    environment:
      CF_DNS_API_TOKEN_FILE: /run/secrets/traefik_cf-dns-api-token
      CF_ZONE_API_TOKEN_FILE: /run/secrets/traefik_cf-zone-api-token
    secrets:
    - traefik_cf-dns-api-token
    - traefik_cf-zone-api-token
  traefik_certs-dumper:
  # See [DargStack: certificates](https://github.com/dargmuesli/dargstack/blob/master/README-skeleton.md#certificates).
    command:
    - file
    - --clean=false
    - --crt-name="$STACK_DOMAIN"
    - --dest=/etc/traefik/acme/
    - --key-name="$STACK_DOMAIN"
    - --source=/etc/traefik/acme/acme.json
    - --version=v2
    - --watch
    environment:
      STACK_DOMAIN: ${STACK_DOMAIN}
    image: ldez/traefik-certs-dumper:v2.7.4@sha256:2936bcc5e365a47d8a642dee64f3ad902439da250f9e62e03298a5e8c2501b00
    volumes:
    - acme_data:/etc/traefik/acme/
version: "3.7"
volumes:
  acme_data:
  # The reverse proxy's certificate data.
    {}
