name: 'CI'

on:
  pull_request:
  push:

jobs:
  build:
    name: DargStack rgen
    uses: dargmuesli/github-actions/.github/workflows/dargstack-rgen.yml@0.40.15
  release-semantic:
    needs: build
    name: Semantic Release
    uses: dargmuesli/github-actions/.github/workflows/release-semantic.yml@0.40.15
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
