name: 'CI'

on:
  pull_request:
  push:

jobs:
  build:
    name: DargStack rgen
    uses: dargmuesli/github-actions/.github/workflows/dargstack-rgen.yml@0.41.5
  release-semantic:
    needs: build
    name: Semantic Release
    uses: dargmuesli/github-actions/.github/workflows/release-semantic.yml@0.41.5
    permissions:
      contents: write
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
