name: 'CI'

on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
    - name: dargstack derive
      run: |
        mkdir ~/scripts/
        wget "https://raw.githubusercontent.com/dargmuesli/dargstack/master/src/dargstack" -O ~/scripts/dargstack
        chmod +x ~/scripts/dargstack
        ~/scripts/dargstack derive
  release-semantic:
    needs: build
    name: Semantic Release
    uses: dargmuesli/github-actions/.github/workflows/release-semantic.yml@0.19.9
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
